[package]
name = "wasm-triangle"
version = "0.1.0"
authors = ["Anuraag Sridhar <anuraag.sridhar@gmail.com>"]

[dependencies]
gl = "0.7"
# TODO: pending https://github.com/tomaka/glutin/pull/962
glutin = { git = "https://github.com/kvark/glutin", branch = "emscripten"}